### ISSUE TITLE
Submatrix module always uses "kernel_size" code

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#11]
Since the "kernel_size" value is default "0", the GetValue("kernel_size") statement on line submatrix.cc:34 will always cause the condition to be true. It should probably be replaced by GetIntValue() or equivalent.
Also, (x0,x1) (y0,y1) are allowed to be equal, but this gives an output size of 0, which the core does not allow. 
Thanks!

**Comment by ikaros-project** [comment]
This is a subtle bug. It used to be possible to check if a value was set using GetValue() but it now always returns the default value. New condition has been substituted. 

Conditions for x0, x1 etc also changed.
