### ISSUE TITLE
Webui: Adding an image crashes ikaros

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#110]
Partial stack:

GroupElement::GetSource(GroupElement * const this, const std::__cxx11::string & name) (/home/trondarild/ikaros/ikaros/Source/Kernel/IKAROS.cc:511)
Kernel::SendUIData(Kernel * const this, char * root, char * args) (/home/trondarild/ikaros/ikaros/Source/Kernel/IKAROS.cc:3875)
Kernel::HandleControlChange(Kernel * const this, char * uri, char * args) (/home/trondarild/ikaros/ikaros/Source/Kernel/IKAROS.cc:4002)
Kernel::HandleHTTPRequest(Kernel * const this) (/home/trondarild/ikaros/ikaros/Source/Kernel/IKAROS.cc:4021)
Kernel::HandleHTTPThread(Kernel * const this) (/home/trondarild/ikaros/ikaros/Source/Kernel/IKAROS.cc:4172)
Kernel::StartHTTPThread(Kernel * k) (/home/trondarild/ikaros/ikaros/Source/Kernel/IKAROS.cc:4183)

**Comment by ikaros-project** [comment]
An example ikg would be useful.

**Comment by ikaros-project** [comment]
Does it have anything to do with sourcemodule in outputs?

Try writing:

`<output name="ABC" source="MODULE.OUTPUT" />`

instead of:

`<output name="ABC" sourcemodule="MODULE" source="OUTPUT" />`

Both should work but this is a likely bug in GetSource().

**Comment by trondarild** [comment]
The following produces the bug on my computer, when I do "add image" in edit mode:
`<?xml version="1.0"?>

<group title="Groupname" >

            <module
                class = "Constant"
                name = "Weight_stn"
                outputsize  = "1"
                data  = "-.25 -.25 -.25"
            />

            <module
                class = "Expression"
                name = "Modifier_stn"
                expression  = "if(y >= x){0} else {x-y}"
                inputs  = "x,y"
                debug="false"
            />

            <module
            class = "Nucleus"
            name = "Subthalamic_nucleus_1"
            epsilon = "0.05"
        />
        <_module
            class = "Nucleus"
            name = "Subthalamic_nucleus_2"
            epsilon = "0.05"
        />
        <_module
            class = "Nucleus"
            name = "Subthalamic_nucleus_3"
            epsilon = "0.05"
        />

    <connection source = "Weight_stn.OUTPUT"  target = "Modifier_stn.y" />
    <connection source = "Subthalamic_nucleus_1.OUTPUT"  target = "Modifier_stn.x" />
    <_connection source = "Subthalamic_nucleus_2.OUTPUT"  target = "Modifier_stn.x" />
    <_connection source = "Subthalamic_nucleus_3.OUTPUT"  target = "Modifier_stn.x" />
    
<view name="view">
</view>
</group>
`

**Comment by ikaros-project** [comment]
This probably fixed now. It appeared to only influence rgb-images. Please test and close if possible.

**Comment by trondarild** [comment]
Will do, check if you have committed

**Comment by ikaros-project** [comment]
Committed!

**Comment by trondarild** [comment]
Still got crashes, but added nullptr checks to all image types, which appears to fix bug

**Comment by ikaros-project** [comment]
Thanks! The bug will go away when all char * have been changed to std::string. Right now it is std::string(NULL) that causes the crash.
