### ISSUE TITLE
Feature request: Nucleus: add size or dimension 

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#113]
To begin with, it would be sufficient to just have an array of nuclei, each with its own input (i.e. no internal interaction between nuclei). This to make it easier to scale up and down the number of nuclei e.g. in basal ganglia model to accommodate varying number of actions.

**Comment by ikaros-project** [comment]
Do they need separate inputs or should they receive the same? One idea would be to have a single input to Nucleus, and add a new module NeuralField that includes topography both input and internal processing.

**Comment by ikaros-project** [comment]
But without some stochastic processing, there is no point in having the same input.

**Comment by ikaros-project** [comment]
There is a conflict between having a single node with multiple inputs, as now, and setting the number of nodes based on the input. If we instead use a parameter for size, there is no guarantee that the input will match the number of nodes. Maybe there should be two modes instad: array: yes/no.

**Comment by trondarild** [comment]
NucleusEnsemble now solves this
