### ISSUE TITLE
Bug in SubMatrix::Tick()

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#13]
On line 99 in SubMatrix.cc:
output[j][i] = input[j+x0][i+y0]; // should be output[j][i] = input[j+y0][i+x0];

also, use of GetFloatValue in Init() gives warnings, so should be changed to Bind().

Thanks!

**Comment by ikaros-project** [comment]
GetFloatValue is correct since it cannot change after init, but the default value should be removed.

**Comment by ikaros-project** [comment]
Fixed in private branch
