### ISSUE TITLE
Feature requirest webui: show group io ports in the group module diagram

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#141]
It would be helpful (and cool) if the io ports of a group are shown in that group's module
diagram. There are several possibilities, e.g. inputs can be shown as small, labeled circles on the left with outputs on the right, or inputs and outputs can be shown as special modules with their respective ports.

**Comment by christianbalkenius** [comment]
This is planed, but not yet implemented.

**Comment by ikaros-project** [comment]
Implemented in version 3.
