### ISSUE TITLE
Feature request webui: Pixel option for images

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#142]
Now images are automatically "blurred" so pixels are not explicitly shown (like with Grid). The option would turn off this blurring, showing the pixels as is. 
Grid could be used, but it is much slower than Image for large matrices.

Thanks!

**Comment by birgerjohansson** [comment]
I think this has to do with the jpeg compression. How large are the matrices?

**Comment by christianbalkenius** [comment]
This has to do with how images are shown by the browsers. I have not found a way to turn this off. You will have to use grid for now.

**Comment by trondarild** [comment]
Ok, thanks
