### ISSUE TITLE
Problem with group parameters, and setting sizes from parameters

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#143]
When setting output sizes from parameters like
size_param_x="size_x" size_param_y="size_y" 

and attempting to set these parameters again via group parameters, the group parameters appear not to propagate through.

Attaching group file with test to reproduce (remove .txt):

[JoinInverse.ikg.txt](https://github.com/ikaros-project/ikaros/files/4522517/JoinInverse.ikg.txt)
[joininverse_test.ikg.txt](https://github.com/ikaros-project/ikaros/files/4522518/joininverse_test.ikg.txt)

Should give following errors:
IKAROS: ERROR: JI.SetSub1 (SetSubmatrix): Source is larger than destination: (3, 3) vs (1, 1).
IKAROS: ERROR: JI.SetSub2 (SetSubmatrix): Source is larger than destination: (3, 3) vs (1, 1).

**Comment by christianbalkenius** [comment]
This appears to work when the target for a parameter is only a single name like "size_x" but not if it includes a specific module like "Base.size_x". The second case should work in the future, though.
