### ISSUE TITLE
Index errors in h_multiply_v

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#15]
Indeces are wrong in h_multiply_v in IKAROS_math.cc, giving erroneous results.

Thanks!

**Comment by ikaros-project** [comment]
Similar to ikaros_private #107

**Comment by trondarild** [comment]
Indeces appear to be wrong again, should be:

t[0] = m[ 0]*v[0] + m[ 1]*v[1] + m[ 2]*v[2] + m[ 3]*v[3];
        t[1] = m[ 4]*v[0] + m[ 5]*v[1] + m[ 6]*v[2] + m[ 7]*v[3];
        t[2] = m[ 8]*v[0] + m[9]*v[1] + m[10]*v[2] + m[11]*v[3];
        t[3] = m[12]*v[0] + m[13]*v[1] + m[14]*v[2] + m[15]*v[3];
        
Correctness can be tested with MatrixRotation, Translation, Scale module tests
