### ISSUE TITLE
Feature request: group files should reside in one place

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#16]
When using ikc files as classes it currently appears to be necessary to copy them into the same directory as the ikc file that uses them. It should be possible to let the group files reside in one place to avoid duplication of files across many directories.

(If this is currently possible, the documentation should be updated to show how it's done)

Thanks!

**Comment by trondarild** [comment]
This can actually be implemented by using os symlinks on mac and linux, though that is of course less elegant.

**Comment by ikaros-project** [comment]
It will be possible to set a path attribute in a module element to select where to find the code. Will appear after the next commit.

`<module name="XYZ" class="ABC" path="/mydirectory/" />`
