### ISSUE TITLE
Webui linux: No webui elements appear for attached model

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#177]
For the attached model, no ui elements appear on startup. If ui elements are removed from the file, it starts up as normal. The model loads normally on mac
[testwebui.ikg.txt](https://github.com/ikaros-project/ikaros/files/9349324/testwebui.ikg.txt)
.

Appears that views are not being built for some reason.

**Comment by ikaros-project** [comment]
Appears at too high update frequency for the WebUI. WebUI may request new data before receiving the old one. This should be prevented.
