### ISSUE TITLE
Feature request: progress indicator on command line 

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#19]
It would be useful for the kernel to print out a progress indicator from 0 to 100% when running long simulations with a set number of steps. E.g. something like this:

Progress: |============........| 60 %

Thanks!

**Comment by birgerjohansson** [comment]
I like this!

**Comment by ikaros-project** [comment]
This has been added, but does not work well in XCode console since it does not handle "\r" correctly. Looks great in terminal!

Should we use -S when we want progress bar and -s otherwise?

**Comment by ikaros-project** [comment]
This function may be removed again later if found to be too irritating.
