### ISSUE TITLE
Cmake errors on linux after clone

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#20]
Attempting to run cmake after a clean clone of ikaros on linux results in the following errors:

CMake Error at Source/Modules/Examples/CMakeLists.txt:4 (add_subdirectory):
  add_subdirectory given source "Sum" which is not an existing directory.

CMake Error at Source/Modules/UtilityModules/CMakeLists.txt:22 (add_subdirectory):
  add_subdirectory given source "Merge" which is not an existing directory.

**Comment by birgerjohansson** [comment]
Fixed (long time ago). Closing issue.
