### ISSUE TITLE
Setsizes() 

### ISSUE THREAD

**Issue by birgerjohansson** [ikaros-project/ikaros#201]
Is this possible to do with the new ikaros? Output should be 16x (max length of MATRIX_1 or MATRIX_2)

void
Transform::SetSizes()
{
    int sy1 = GetInputSizeY("MATRIX_1");
    int sy2 = GetInputSizeY("MATRIX_2");

    if(sy1 == unknown_size || sy2 == unknown_size)
        return;
        
    int sy = max(sy1, sy2);

    SetOutputSize("MATRIX", 16, sy);
    SetOutputSize("OBJECT_ID", sy);
    SetOutputSize("FRAME_ID", sy);
}

**Comment by ikaros-project** [comment]
This is not possible. We could add functions like max to the size values in the ikc but we would need to motivate it with more use cases.

**Comment by ikaros-project** [comment]
We need to  bring back SetSizes in modules in situations where the size it not known before Init().

**Comment by ikaros-project** [comment]
New (untested) version:

```C++
void
Transform::SetSizes()
{
   Bind(m1, "MATRIX_1"); // Assuming matrices are already defined
   Bind(m2, "MATRIX_2");
   Bind(m, "MATRIX");
   Bind(object_id, "OBJECT_ID");
   Bind(frame_id, "FRAME_ID");

   im1.empty())
        return;

   if(m2.empty())
        return;

    int sy = std::max(m1.size_y(), m2.size_y());
    m.reshape(16, sy);
    object_id.reshape(sy);
    frame_id(sy);
}
```

**Comment by ikaros-project** [comment]
SetSizes will be completely removed again and replaced with function that sets parameters that can be accessed by the size attribute instead.
