### ISSUE TITLE
log_level is set to 5

### ISSUE THREAD

**Issue by birgerjohansson** [ikaros-project/ikaros#210]
When setting log_level at command line, the log_level changes to 5 during Ikaros startup.

**Comment by ikaros-project** [comment]
The original bug is removed, but log_level is apparently saved with the file so the value 5 may still remain.

**Comment by ikaros-project** [comment]
This appears to be working now but there may still be log_level=5 in files saved previously that need to be removed manually.

**Comment by birgerjohansson** [comment]
I have removed all log_level parameters from the ikg file. Still after some time it switches to 5.

Setting log_level = 10 as an argument gives:

ikaros: Pruning ExperimentalSetup.SR.OUTPUT=>ExperimentalSetup.Epi.LED.MOUTH_INTENSITY
ikaros: Pruning ExperimentalSetup.OneHotVector.OUTPUT=>ExperimentalSetup.Epi.SoundOutput.TRIG
Log_level: 10
ikaros:         Component::SetSizes (ExperimentalSetup)
Log_level: 10
ikaros:                 Component::SetInputSizes (ExperimentalSetup)
Log_level: 10
ikaros:                 Component::SetOutputSizes (ExperimentalSetup)
Log_level: 5
Log_level: 5

**Comment by birgerjohansson** [comment]
In   SetParameters() loglevel is 5. Later in init() it switches to 10. And then switches back to 5.
