### ISSUE TITLE
SizeList expressions with size_x are not handled correctly

### ISSUE THREAD

**Issue by christianbalkenius** [ikaros-project/ikaros#213]
e.g. size = "INPUT.size_x, INPUT_size_y" does not work,.

**Comment by birgerjohansson** [comment]
Maybe change this line to
https://github.com/ikaros-project/ikaros/blob/8a521dbb2d3f476d8f63e03daec7eb4d743bcb07/Source/Kernel/ikaros.cc#L773


`            if(ends_with(e, ".size") || ends_with(e, ".size_x") || ends_with(e, ".size_y")) // special case: use shape function on input and push each dimension on list
`
