### ISSUE TITLE
Get a parameter in SetParamters()?

### ISSUE THREAD

**Issue by birgerjohansson** [ikaros-project/ikaros#216]
I think it is not possible to resolve a parameter in setParamters(). 

I want to get the output_format parameter and use it to set the output size. If output_format  = "xyz" output.size_x should be 3. If I set output_format = "matrix"  the output size should be 16. However, output format.as_int() is always 0.  

Any suggestions? This was previously done in the setSizes() function (ikaros-2).
 void
    SetParameters() // get size of output
    {
        Bind(size_x, "size_x");
        Bind(size_y, "size_y");
        Bind(outputFormat, "output_format"); // not working. Parameter is not resolved in setParameter.

        switch (outputFormat.as_int())
        {
        case 0: // xyz
            size_x = size_xyz;
            break;
        case 1: // xyzaxayaz
            size_x = size_xyzaxayaz;
            break;
        case 2: // axayaz
            size_x = size_axayaz;
            break;
        case 3: // matrix
            size_x = size_matrix;
            break;
        case 4: // quaternion
            // Not implemented yet ...
            break;
        default:
            break;
        }
    }

**Comment by ikaros-project** [comment]
Add GetValue and SetValue to Component/Module class.

**Comment by ikaros-project** [comment]
Functions GetValue() and SetParameter() already exists and could probably be used for this.

GetValue(key) returns the value for key as a string in the context of the current component and does some value resolution.

Alternatively, LookupKey(key) can be used that only retrieves the value and does not process it at all.

The parameter could then be set with SetParameter(ket, value) where value must be a string.

This needs to be tested.

**Comment by ikaros-project** [comment]
if(GetValue("output_format") == "xyz")
   etc. etc.

Should work but all values must be strings. Should we add SetParameter for other types too, or is it OK to use Bind in that case?

**Comment by ikaros-project** [comment]
Closing for now. Reopen if this solution is not sufficient.
