### ISSUE TITLE
Feature request: parameterization of connection delays in groups 

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#23]
Sometimes delays on internal connections in a group depend on outside factors. It would be useful to be able to target connections with parameters to set such delays.

Particular use case in question is setting correct delay for a reward signal, when the signal generator is internal to the group.

Thanks!

**Comment by ikaros-project** [comment]
This is planned for the next version of the kernel

**Comment by ikaros-project** [comment]
The new variable mechanism probably handles this. 

```
<connection delay="@my_parameter_set_elsewhere" ... />
```
