### ISSUE TITLE
Feature request: allow webgui to work more smoothly with remote hosts

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#26]
If ikaros runs on a remote host (typically in another country), the webui struggles to work smoothly, and the screen redraws often blanks out the screen. It would be useful if the components could tolerate the delays that are incurred when the host is not run locally.

**Comment by ikaros-project** [comment]
The simplest solution would probably be to add a time-out parameter when the WebUI is started. The time-out is currently fixed.

**Comment by ikaros-project** [comment]
WebUI 2.0 is rewritten to allow arbitrary slow connections.
