### ISSUE TITLE
errors in module tutorial on webpage

### ISSUE THREAD

**Issue by rasmusolofzon** [ikaros-project/ikaros#32]
Regarding http://www.ikaros-project.org/articles/2011/moduletutorial/ , making issue here

A couple of issues discovered while following the tutorial:
- There now exists a module called Sum, name of tutorial module clashes with this
- No guidance on where in the file structure to place the written files or how to add them through cmake (preferably include location (Source/UserModules/) and which cmake files to edit (the one in UserModules and an own in the module's folder) and how, and clarify that (cmake and) make should be done after any changes)
- Under 'Runtime', the test ikc file is named Sum_test.ikc, however at runtime a file called network.ikc is used
- in Sum.h, remove 'char *name' from constructor at line 31, also remove the same from statement at line 33

**Comment by ikaros-project** [comment]
These things have been corrected in the tutorial.
