### ISSUE TITLE
DepthPointList example not working

### ISSUE THREAD

**Issue by fbontin** [ikaros-project/ikaros#34]
The example for DepthPointList is not working. Probably due to some typos and that it tries to use DepthBlobList instead of DepthPointList. Regarding the file here [https://github.com/ikaros-project/ikaros/blob/master/Source/Modules/VisionModules/DepthProcessing/DepthPointList/Examples/DepthPointList_test.ikc](url)

**Comment by ikaros-project** [comment]
Can't reproduce.
