### ISSUE TITLE
Perceptron learning rule values list should have "default" as first entry

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#35]
In Perceptron.ikc, the list is currently:
"rosenblatt/rosenblatt_margin/may/alpha_lms/mu_lms/delta"
but should be
"default/rosenblatt/rosenblatt_margin/may/alpha_lms/mu_lms/delta" (as it is in the cc file)

Thanks!

**Comment by ikaros-project** [comment]
This is now corrected.
