### ISSUE TITLE
Can't compile Ikaros on Fedora 20 x64

### ISSUE THREAD

**Issue by fohria** [ikaros-project/ikaros#4]
There seems to be an issue with how Fedora handles the linking of cblas libraries so compilation fails.

I installed the following dependencies (I think some of them needed RPM Fusion repositories):

cmake
gcc-c++
libjpeg-turbo-devel
gsl-devel
libpng-devel
blas-devel
ffmpeg-devel
libfreenect
libfreenect-devel

I then had to symlink /usr/include/ffmpeg/libavcodec (also libavformat, libavutil and libswscale) to /usr/include for the compiler to find these libraries.

The error I receive is that cblas functions cannot be found. These are the last few lines:

> IKAROS_Math.cc:(.text+0x307f): undefined reference to `cblas_sgemm'
> CMakeFiles/ikaros.dir/Source/Kernel/IKAROS_Math.cc.o: In function `ikaros::dot(float*, float*, int)':
> IKAROS_Math.cc:(.text+0x30e4): undefined reference to `cblas_sdot'
> collect2: error: ld returned 1 exit status
> make[2]: *** [../Bin/ikaros] Error 1
> make[1]: *** [CMakeFiles/ikaros.dir/all] Error 2
> make: *** [all] Error 2

If I understand it correctly after some googling, this is because of changed links for cblas/atlas libraries in fedora so these need to be linked manually in some way for compilation to work.

At this point I gave up however since my knowledge of pkg-config and cmake doesn't go much further than writing "cmake .." :)

**Comment by ikaros-project** [comment]
Since the BLAS libraries are installed in a non-default location they are not found by the compile script. We will not changed in the standard script but has to be done individually for each non-standard installation.

A temporary solution is to disable BLAS. It can be removed by changing the #defined in the IKAROS_System.h file.
