### ISSUE TITLE
Non working _test.ikc files

### ISSUE THREAD

**Issue by birgerjohansson** [ikaros-project/ikaros#42]
- [ ] ../Source/Modules/ANN/RNN/Examples/RNN_test.ikc
- [ ] ../Source/Modules/LearningModules/LearningModule/Examples/LearningModule_test.ikc
- [x] ../Source/Modules/BrainModels/EyeModel/Examples/EyeModel_test.ikc

**Comment by ikaros-project** [comment]
Will need to be replaced with a new one for version 3.
