### ISSUE TITLE
EyeTribe is required by cmake but is not mentioned in install instructions

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#45]
Please add instructions on how to install EyeTribe to install instructions on ikaros-project.org, or make it optional for cmake instead of required.

**Comment by birgerjohansson** [comment]
It is optional. I use CMake without compiling theEyeTribe module.

Let me check the script again.

**Comment by birgerjohansson** [comment]
Please try again. I updated the script.

**Comment by trondarild** [comment]
Works now thanks!
