### ISSUE TITLE
Feature request: button grid

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#46]
It would be useful to specify a clickable grid where each cell can be toggled on or off and which modifies e.g. a constant matrix. Optionally, each cell could be modified between a max and min value by clicking and dragging. Visually the cell should change intensity according to its value.

Thanks!

**Comment by ikaros-project** [comment]
This functionality is now available in the grid widget by setting

`parameter = "data"`

for a grid showing the output from a Constant module.
