### ISSUE TITLE
Feature request: mathematical expression module

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#50]
This is a note-to-self issue:
A module which can parse mathematical expressions and generate the necessary inputs. This would make it easy to use e.g. difference equations to simulate various physical processes. 
The module should assume array inputs.

Example expression to parse:
damped oscillator: dT*(-position*k-velocity*d)/m 
this would generate inputs:
dT, position, k, velocity, d, m
and recognize operators *, -, (,), /,+

**Comment by ikaros-project** [comment]
A library like ExprTk (http://partow.net/programming/exprtk/index.html) or some of the librearies here (https://github.com/ArashPartow/math-parser-benchmark-project) could potentially be used for this.

If this is sufficiently efficient, simple modules could be defined using mathematical expression.

**Comment by trondarild** [comment]
Looks good, though it appears that variables must be separately supplied. But I guess that is acceptable!

**Comment by ikaros-project** [comment]
Great work!
