### ISSUE TITLE
WebUI is cutting text (coordinate system, min, max +3 digits)

### ISSUE THREAD

**Issue by birgerjohansson** [ikaros-project/ikaros#58]

**Comment by ikaros-project** [comment]
Need an example.

The solution may be to change the margins of the widget.

**Comment by ikaros-project** [comment]
The space around the graph is not supposed to change automatically to keep the graphs aligned. But can be changed using a style parameter in the view inspector:

`--margin-left:50px`

or in the IKC-file:

`<bar-graph ... style="--margin-left:50px" ...>`

Alternatively, the decimals can be removed:

`<bar-graph ... style="--decimals: 0" ...>`

Perhaps there should be an option to change the margin automatically.
