### ISSUE TITLE
Can't get present position data from Dynamixel servos when using explicit servo id

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#6]
When using explicit servo ids, getting the FEEDBACK_PRESENT_POSITION value does not return expected value. In the example referenced below, used only one explicitly addressed servo, but with different ids to test. Also tried with 3 servos, but then could only get present position from servo id 1.

Example used: 
https://github.com/BjarniB/ikaros/blob/master/Source/UserModules/RobotRecorder/Examples/RobotRecorder_example_explicit_adr_single_test.ikc

In example :
        servo_id = "1 2 3" // 2 is used
        _servo_id = "1" // doesn't work
        _servo_id = "2" // doesn't work
        _servo_id = "3" // doesn't work
        _servo_id = "1 2" // 2 is used
        _servo_id = "2 3" // 2 is used
        _servo_id = "3 2" // 2 is used
        _servo_id = "3 2 1" // 2 is used

with module https://github.com/BjarniB/ikaros/blob/master/Source/UserModules/RobotRecorder

**Comment by ikaros-project** [comment]
Is this still a problem?

**Comment by birgerjohansson** [comment]
No
