### ISSUE TITLE
WebUI is stuck in timeout and cannot connect with ikaros if frame rate too slow

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#71]
To reproduce:
Insert e.g. sleep(3000) in a module so frame rate takes 3 sec (limit is probably more like 500-1000ms). 

Web ui will then not update and will be stuck in timeouts.

**Comment by ikaros-project** [comment]
The WebUI should now work with a frame rate up (down?) to a second. This will be dynamically adjusted in the future.
