### ISSUE TITLE
If ikc file does not exist ikaros crashes.

### ISSUE THREAD

**Issue by birgerjohansson** [ikaros-project/ikaros#82]
Including b.ikc (with a non existing b.ikc) in a.ikc gives segmentation fault. 
Should give a warning. "b.ikc does not exist"

**Comment by ikaros-project** [comment]
include with <?include?> or <module>?

**Comment by birgerjohansson** [comment]
Replicate it by changing
    <?include file="included_file_1.ikc" ?>
to 
    <?include file="included_file_1_haha_just_kidding.does.not.exist.ikc" ?>

in ikaros/Examples/ikc-Features/include.ikc

**Comment by ikaros-project** [comment]
Massive exception handling coming...
