### ISSUE TITLE
target_offset/source_offset in input/output in groups?

### ISSUE THREAD

**Issue by birgerjohansson** [ikaros-project/ikaros#85]
Should it be possible to set offset in group input tags? Similar as in connections.

**Comment by ikaros-project** [comment]
Duplicate of #81

**Comment by birgerjohansson** [comment]
I think this is conceptually important. We need to implement this or make it clear that the source offset features does not apply for inputs. A workaround would be to use absolute paths into the group.

**Comment by ikaros-project** [comment]
Handled by internal group connections in version 3.
