### ISSUE TITLE
Webui: Feature request: transparency value for images

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros#89]
Modifying transparency of e.g. background images would improve readability for a view when widgets are placed on top of it.

**Comment by ikaros-project** [comment]
Do you mean that you want a transparency parameter for images?

**Comment by trondarild** [comment]
> Do you mean that you want a transparency parameter for images?

Yes please : )

**Comment by ikaros-project** [comment]
It is already possible to set something like "opacity:0.5" in the style field of an image in the webui. It is unclear it this can be done in the IKG file however or if it is saved. A separate transparence parameter would be better.
